spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties.hibernate:
      format_sql: true
    show-sql: true
jwt:
  secret:
    key: ${JWT_SECRET}

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace